spring:
  application:
    name: spring-outh2-social-login
  security:
    user:
      name: ${USERNAME:default}
      password: ${PASSWORD:pass123}

    outh2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read-user
              - read-email



github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}